export const STORE_INBOX_DATA = 'STORE_INBOX_DATA';
export const GET_FILTER_DATA = 'GET_FILTER_DATA';
export const SET_SELECTED_FOLDER = 'SET_SELECTED_FOLDER';
export const REDUCE_UNREAD_COUNT = 'REDUCE_UNREAD_COUNT';
export const FLAG_CLICK_ACTION = 'FLAG_CLICK_ACTION';
export const DELETE_MAIL_ACTION = 'DELETE_MAIL_ACTION';